config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/homepage'

  get 'home/dashboard'

  get 'profile/:user_id' => 'home#profile' , as: :profile
  
  unauthenticated do
    root to: "home#homepage"
  end
    
  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root 
  end

  resources :messages

  devise_for :users

end

app/models/message.rb
class Message < ActiveRecord::Base
  
  belongs_to :user
  validates :message, presence: true, length: { maximum: 100 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  
  validates :phone_number, presence: true, length: { maximum: 50 }
  validates :username, presence: true, uniqueness: { case_sensitive: false },
            :format => { :with =>/\A[a-z0-9A-Z]+\z/ ,
            :message=>"Only letters and numbers with no spaces allowed" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
#  This will allow devise to interact with the database with those parameters 
  before_filter :configure_permitted_parameters, if: :devise_controller?

 protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:email, :password)
    end
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:username, :phone_number, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:username, :phone_number, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
  end

  def dashboard
  end

  def profile
    @user = User.find(params[:user_id])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.message_from = current_user.id
    
    require 'nexmo'

    nexmo = Nexmo::Client.new(key: '59b9c3cb', secret: '064b2ae8 ')
  
    @user = User.find(params[:message][:user_id])
    
    nexmo.send_message(from: 'Ruby', to: @user.phone_number , text: 'Hello World')

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:message, :user_id, :message_from)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/dashboard.html.erb
<h1>Home#dashboard</h1>
<p>Find me in app/views/home/dashboard.html.erb</p>

app/views/home/homepage.html.erb
<h1>Home#homepage</h1>
<p>Find me in app/views/home/homepage.html.erb</p>

app/views/home/profile.html.erb
<h1><%= @user.username %></h1>

<%= form_for(@message) do |f| %>
   
   <div class="field">
     <%= f.hidden_field :user_id, :value=>@user.id %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="actions" %>
    <%= f.submit "Send message", :class=> "btn btn-success" %>
  </div>  
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messageme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  
</head>
<body>
  
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Messageme</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Home", root_url %></li>
    <% if user_signed_in? %>
        <li><%= link_to "Profile", profile_path(current_user) %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, :method=>:delete %></li>
  <%else%>
  <li><%= link_to "Sign_in", new_user_session_path %></li>
  <li><%= link_to "Sign_up", new_user_registration_path %></li>
  <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <div class="container">
<%= yield %>
  </div>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :message_from %><br>
    <%= f.number_field :message_from %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th>Message from</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.message %></td>
        <td><%= message.user_id %></td>
        <td><%= message.message_from %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<% if @message.message_from == nil %>
   <% @messagefrom = "Someone" %>
<%else%>
  <% @user= User.find(@message.message_from) %>
  <% @messagefrom = @user.username %>
<%end%>

<h1> <%= @messagefrom %> said <%= @message.message %> to <%= @message.user.username %> </h1>

<a href="/profile/<%= @message.user.id %>" > Back to <%= @message.user.username %>  </a>